language: python
python:
  - "2.7"

os:
  - linux

cache:
  directories:
  - $HOME/build_tools

install:
  - test -d $HOME/build_tools ||( mkdir $HOME/build_tools && wget http://mirrors.cdn.adacore.com/art/5739cefdc7a447658e0b016b -O $HOME/build_tools/gnat-gpl-2016-x86_64-linux-bin.tar.gz)
  - tar -xf $HOME/build_tools/gnat-gpl-2016-x86_64-linux-bin.tar.gz
  - export PATH=$PATH:$PWD/gnat-gpl-2016-x86_64-linux-bin/bin/

script:
  - $PWD/gnat-gpl-2016-x86_64-linux-bin/bin/gprbuild --version
  - python $PWD/testsuite/run.py
